#########> Dashboard routes <#########
kira_log_viewer.dahsboard.index:
  path: "/index"
  controller: Kira0269\LogViewerBundle\Controller\DashboardController::list
  methods: [GET]

#########< Dashboard routes >#########
