#########> Dashboard routes <#########
kira_log_viewer.dahsboard.index:
  path: "/"
  controller: Kira0269\LogViewerBundle\Controller\DashboardController::index
  methods: [GET]

#########< Dashboard routes >#########
