services:
  _defaults:
    public: false

  Kira0269\LogViewerBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
    calls:
      - [setContainer, ['@service_container']]

  Kira0269\LogViewerBundle\Services\LogParser\LogParserInterface:
    class: Kira0269\LogViewerBundle\Services\LogParser\LogParser
    arguments:
      $logsDir: ''

  kira_log_viewer.log_parser.default:
    alias: Kira0269\LogViewerBundle\Services\LogParser\LogParserInterface
    public: true
